apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-site
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app-site
  template:
    metadata:
      labels:
        run: app-site
    spec:
      containers:
      - name: app-site
        image: appconsult
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
