apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-site
images:
- name: app-site
  newName: nandocloud/app-site
  newTag: dfe3017f6f05e562542acdbe6f9bd03bd8263387
- name: app-site
  newName: app-site
  newTag: latest
